### ISSUE TITLE
Update for Julia 1.x?

### ISSUE THREAD

**Issue by mpastell** [lucianolorenti/BibTeXFormat.jl#4]
I'm adding support for citations to Weave.jl https://github.com/mpastell/Weave.jl/pull/185 . I now have a version with a parser for citation and very basic formatting for output.

Looks like this package would be very useful for proper formatting of the bibliography! Do you have any plans to update for Julia 1.x and registering the package?

**Comment by lucianolorenti** [comment]
Hi. I merged your PR.  I made a few changes and the tests are starting to pass. There is still some work to do. I will find time the next days to keep updating the code.

**Comment by mpastell** [comment]
Thanks! it's always a lot of work to update. Good to hear that you're working on it!

**Comment by lucianolorenti** [comment]
Hi. I don't know if you are still interested. I updated it a bit more and the output is being generated in julia 1.2. Now the official BibTex parser is being used. There are some tests that still fails because I could not find a package like  [pylatexenc](https://pypi.org/project/pylatexenc/)
