### ISSUE TITLE
[FR] Handling accents

### ISSUE THREAD

**Issue by tlienart** [lucianolorenti/BibTeXFormat.jl#6]
Hello,

The package doesn't seem to handle accents properly e.g.: 

```
[Maw004] Jean Mawhin. Les fondements de la m \\'e canique en amont et en aval de poincar \\'e . r \\'e actions belges \\`a l’exp \\'e rience du pendule de foucault. Philosophiques, 2004. 
```

it might be difficult to encode the full list but maybe the common ones could be added like ``\'e, \^e, \"a`` etc?

**Comment by tlienart** [comment]
actually this python script seems to do the lot: https://github.com/hayk314/LaTex-handler/blob/master/LaTexAccents.py it's MIT licensed so could be ported?

**Comment by lucianolorenti** [comment]
I ported the LatexAccents.py and used in the richtextelement part.
There are a few tests that are still failing.
Unfortunately, I have neither the time nor the interest to keep maintaining this package

**Comment by tlienart** [comment]
Nice, I just had a look at `accents.jl`, thanks.

I might fork the package and make it into a plug-in for Franklin, creds will remain attributed to you.
